version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_NAME: ${POSTGRES_NAME}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
    working_dir: /code/app
    command: sh ./startup/entrypoint.sh
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  
  react:
    build:
      context: ./app/front
      dockerfile: Dockerfile
    volumes:
      - ./front:/front
    ports:
      - "3000:3000"
    command: npm start

volumes:
  db: