version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_NAME: ${POSTGRES_NAME}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
    working_dir: /code/app
    command: sh ./startup/entrypoint.sh
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  react:
    build:
      context: ./app/front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - react

volumes:
  db:
