FROM node:20-alpine

WORKDIR /app

RUN apk update && apk add --no-cache postgresql-client

COPY package.json package-lock.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 5173

ENV NODE_ENV=development

ENTRYPOINT ["./scripts/entrypoint.sh"]
