FROM node:20-alpine

WORKDIR /app

RUN apk update && apk add --no-cache postgresql-client

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production

ENTRYPOINT ["./scripts/entrypoint.sh"]
